# yaml-language-server: $schema=https://json.schemastore.org/pnpm-workspace
---
packages:
  - internal/*
  - packages/*

catalog:
  "@biomejs/biome": 2.3.10
  "@types/bun": ^1.3.5
  "@types/node": ^25
  "@typescript/native-preview": latest
  "@vitest/coverage-v8": ~4.0.16
  dprint: latest
  publint: ^0.3.16
  tsdown: ~0.18.1
  typescript: 5.9.3
  unplugin-unused: ^0.5.6
  vitest: ~4.0.16

gitChecks: false
publishBranch: master

onlyBuiltDependencies:
  - dprint
  - esbuild
  - lefthook
  - publint
  - unplugin-unused
