# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json
---
packages:
  - packages/*
  - internal/*

onlyBuiltDependencies:
  - dprint
  - esbuild

catalog:
  "@typescript/native-preview": latest
  typescript: ^5
  "@biomejs/biome": 2.3.8
  dprint: latest
  vitest: ~4.0.15
  tsdown: ~0.17.3
  "@types/node": ^25
