---
name: Setup pnpm
description: Installs pnpm and sets up Node.js with pnpm cache
inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: "22"
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
