name: "Setup pnpm"
description: "Installs pnpm, sets up Node.js with pnpm cache, and installs dependencies"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "20"
  pnpm-version:
    description: "pnpm version to install"
    required: true
    default: "10"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install
      shell: bash
